baseURL = "https://soles21.github.io/testhugo/"
languageCode = "en-us"
publishDir = "docs"
paginate = 6
theme= "coHub"
title = "Xcellerate BV - IT experts on a mission to help you gain competitive advantage through technology. We deliver products and services that boost productivity &amp; agility of your business."
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Diensten"
  url= "#gallery"
  weight = 1
  [[menu.Main]]
  name = "Wie zijn we?"
  url= "#service"
  weight = 2
  [[menu.Main]]
  name = "Productivity Shop"
  url= "about"
  weight = 3
  [[menu.Main]]
  name = "Tools"
  url= "#blog"
  weight = 4
  [[menu.Main]]
  name = "Contact"
  url= "#pricing"
  weight = 5
  [[menu.Main]]
  name = "Mijn Account"
  url= "#faq"
  weight = 6
  [[menu.Main]]
  name = "Support"
  url= "contact"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} Xcellerate BVBA - BE 0578.884.320"
  formspreeURL = "https://formspree.io/mbjwlead"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo.png"
  footerlogo = "images/logo.png"
  footerDescription = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit quia ab, natus fugiat voluptas saepe ipsum animi officiis in molestiae?"

  [params.address]
  address = "Wingenesteenweg 7 - bus 001 B-8750 Zwevezele"
  email = "support@xcellerate.be"
  openingDesc = "Give us a call or drop by anytime, we endeavour to answer all enquiries within 24 hours on business days."
  openingHours = "We are open from 7am — 7pm week days."
  phone = "+32 51 499 001"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "45.4502528"
  longitude = "-122.783407"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-skype"
  url = "https://skype.com/"
  weight = 3
  [[params.social]]
  icon = "ti-linkedin"
  url = "https://www.linkedin.com/"
  weight = 4
  
  
